### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by yabberyabber** [KyleD973/MotionProfile#2]
Here's a handful of ways to improve the usefulness of the tests that you already wrote:

 * Test a bunch of profiles.  Rather than hard coding one profile to test, loop through a bunch of different profiles.  Try some profiles with really big v_max; try some profile with really small v_max; try some profiles with a negative dist; etc etc etc.  The best way to do this will probably involve a bunch of nested loops.
 * Now that you're running more tests, you're going to have more output and it's going to take more time to look at all that output.  Instead of calling `System.out.println` on the result of the tests, call `assert` on the result of each test.  
 * Why did you name the iterator `t_rand`?  Rand sounds like random https://github.com/KyleD973/MotionProfile/blob/master/MotionProfile/src/main.java#L45

Once this works we can integrate it into the robot code and it should work as a drop-in replacement for the existing motion profile generator.  Good work! :+1:

**Comment by KyleD973** [comment]
Can you look at my assert statements and the loops too? Every time I run it there's always an exception  which is what we want. But at least try to look and see if those makes sense. Thanks!

**Comment by yabberyabber** [comment]
The syntax for the assert statement is correct

**Comment by KyleD973** [comment]
You should check everything again. I just integrated negative distances for both profiles.
